services:

  oikos:
    build: .
    image: atsob/oikos:latest
    container_name: oikos
    ports:
      - "8080:8000"
    environment:
      - DB_NAME=Finance
      - DB_USER=admin
      - DB_PASSWORD=31.12.1969
      - DB_HOST=host-gateway
      - DB_PORT=5432
      - DB_TIMEZONE=Europe/Athens
      - APP_DATA_DIR=/app
      - OLLAMA_IP=127.0.0.1
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=llama3.2:3b
      - PERSIST_DIR=/app/storage_rag
    extra_hosts:
      - "host-gateway:host-gateway"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  oikos_scheduler:
    build: .
    image: atsob/oikos:latest
    container_name: oikos_scheduler
    environment:
      - DB_NAME=Finance
      - DB_USER=admin
      - DB_PASSWORD=31.12.1969
      - DB_HOST=host-gateway
      - DB_PORT=5432
      - DB_TIMEZONE=Europe/Athens
      - APP_DATA_DIR=/app
      - OLLAMA_IP=127.0.0.1
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=llama3.2:3b
      - PERSIST_DIR=/app/storage_rag
    extra_hosts:
      - "host-gateway:host-gateway"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: python scheduler.py
    restart: unless-stopped
