"""Reference data seeded into a brand-new (empty) database on first startup.

Generated once from a real, populated install and hand-curated to strip anything
personal or identifying (family names, specific accounts, named individuals, hyper-local
shops) -- see CHANGELOG for context. Not auto-regenerated; edit the literals directly if
the seed set needs to change.
"""

# (id, quality, description, moodys, s_p, fitch) -- the standard long-term credit rating
# scale used across the industry; not present in Oikos.sql's own base inserts, so without
# this Institutions/Issuers can't carry a rating (both FK into this table).
CREDIT_RATINGS_LT = [
    (1,  'Prime',                'Investment Grade', 'Aaa',  'AAA',  'AAA'),
    (2,  'High Grade',           'Investment Grade', 'Aa1',  'AA+',  'AA+'),
    (3,  'High Grade',           'Investment Grade', 'Aa2',  'AA',   'AA'),
    (4,  'High Grade',           'Investment Grade', 'Aa3',  'AA-',  'AA-'),
    (5,  'Upper Medium Grade',   'Investment Grade', 'A1',   'A+',   'A+'),
    (6,  'Upper Medium Grade',   'Investment Grade', 'A2',   'A',    'A'),
    (7,  'Upper Medium Grade',   'Investment Grade', 'A3',   'A-',   'A-'),
    (8,  'Lower Medium Grade',   'Investment Grade', 'Baa1', 'BBB+', 'BBB+'),
    (9,  'Lower Medium Grade',   'Investment Grade', 'Baa2', 'BBB',  'BBB'),
    (10, 'Lower Medium Grade',   'Investment Grade', 'Baa3', 'BBB-', 'BBB-'),
    (11, 'Speculative',          'Non-Investment Grade', 'Ba1', 'BB+', 'BB+'),
    (12, 'Speculative',          'Non-Investment Grade', 'Ba2', 'BB',  'BB'),
    (13, 'Speculative',          'Non-Investment Grade', 'Ba3', 'BB-', 'BB-'),
    (14, 'Highly Speculative',   'Non-Investment Grade', 'B1',  'B+',  'B+'),
    (15, 'Highly Speculative',   'Non-Investment Grade', 'B2',  'B',   'B'),
    (16, 'Highly Speculative',   'Non-Investment Grade', 'B3',  'B-',  'B-'),
    (17, 'Substantial Risk',     'Non-Investment Grade', 'Caa1', 'CCC+', 'CCC+'),
    (18, 'Substantial Risk',     'Non-Investment Grade', 'Caa2', 'CCC',  'CCC'),
    (19, 'Substantial Risk',     'Non-Investment Grade', 'Caa3', 'CCC-', 'CCC-'),
    (20, 'Very High Risk',       'Non-Investment Grade', 'Ca',  'CC',  'CC'),
    (21, 'In Default',           'Non-Investment Grade', 'C',   'C',   'C'),
]

# (shortname, name)
CURRENCIES = [('AED', 'EMIRATI DIRHAM'),
 ('ALL', 'ALBANIAN LEI'),
 ('BGN', 'BULGARIAN LEV'),
 ('BRL', 'BRAZILLIAN REAL'),
 ('CAD', 'CANADIAN DOLLAR'),
 ('CHF', 'SWISS FRANK'),
 ('CYP', 'CYPRIOT POUND'),
 ('EGP', 'EGYPTIAN POUND'),
 ('EUR', 'EURO CURRENCY'),
 ('GBP', 'UNITED KINGDOM BRITISH POUND'),
 ('HKD', 'HONG KONG DOLLAR'),
 ('HUF', 'HUNGARIAN FIORINT'),
 ('ILS', 'ISRAELI SHEKEL'),
 ('JPY', 'JAPANESE YEN'),
 ('KRW', 'SOUTH KOREAN WON'),
 ('NOK', 'NORWEGIAN KRONE'),
 ('PLN', 'POLISH ZLOTY'),
 ('RON', 'ROMANIAN LEU'),
 ('RSD', 'SERBIAN DINAR'),
 ('RUB', 'RUSSIAN RUBLE'),
 ('SEK', 'SWEDISH KRONA'),
 ('SGD', 'SINGAPORE DOLLAR'),
 ('TRY', 'TURKISH LIRA'),
 ('TWD', 'TAIWAN DOLLAR'),
 ('USD', 'UNITED STATES DOLLAR')]

# (name, type, bic_code, website, notes, moodys, s_p, fitch)
INSTITUTIONS = [('ABN AMRO BANK', 'Bank', 'ABNANL2A', 'www.abnamro.nl', None, 'Aa3', 'A', 'A'),
 ('CAPITAL.COM', 'Broker', 'CPLMCY22', 'www.capital.com', None, None, None, None),
 ('CITIBANK', 'Bank', 'CITIGRAA', 'www.citibank.gr', None, 'Aa3', 'A', 'A+'),
 ('COINBASE', 'Crypto Exchange', None, 'www.coinbase.com', None, 'Ba2', 'BB', None),
 ('CRYPTO.COM', 'Crypto Exchange', None, 'www.crypto.com', None, None, None, None),
 ('FXPRO', 'Broker', 'FXPRCY22', 'www.fxpro.com', 'Private Entity - CFDs Broker', None, None, None),
 ('INTERACTIVE BROKERS',
  'Broker',
  'IBKRUS33',
  'www.interactivebrokers.com',
  None,
  None,
  'BBB+',
  'BBB+'),
 ('J.P. MORGAN SE', 'Bank', 'CHASEDEFXXX', None, None, 'Aa2', 'AA-', 'AA'),
 ('NN', 'Insurance', None, 'my.nnhellas.gr', 'Μητρική: NN Group', 'A1', 'A', None),
 ('PAYPAL', 'Other', 'PAYPBEB1', 'www.paypal.com', None, 'A3', 'A-', None),
 ('REVOLUT', 'Bank', 'REVOLT21', 'www.revolut.com', None, 'Baa3', None, None),
 ('SAXO BANK',
  'Bank',
  'SAXODKKK',
  'www.saxotrader.com',
  'SAXO BANK A/S PHILIP HEYMANS ALLE 15\n2900 HELLERUP DENMARK',
  None,
  'A-',
  None)]

# (tax_category, display_name, gains_taxable, gains_rate, gains_tax_code,
#  dividend_local_tax_rate, dividend_wht_creditable, reinvest_taxable, income_tax_rate,
#  notes, show_in_capital_gains)
TAX_CATEGORY_RULES = [('Belgium Regulated Shares',
  'Belgium Regulated',
  False,
  None,
  None,
  '30.00',
  True,
  False,
  None,
  None,
  True),
 ('Bond',
  'Bond / Fixed Income',
  False,
  None,
  None,
  None,
  False,
  False,
  '15.00',
  'Coupon interest taxed at 15%. Capital gains treatment depends on instrument.',
  False),
 ('CD',
  'Time Deposit / CD',
  False,
  None,
  None,
  None,
  False,
  False,
  '15.00',
  'Interest income from time deposits and CDs taxed at 15% (withheld at source).',
  False),
 ('Crypto',
  'Cryptocurrency',
  True,
  '15.00',
  None,
  None,
  False,
  True,
  '15.00',
  'Capital gains taxed at 15%. Staking and other income taxed at 15% as income at receipt.',
  True),
 ('Foreign Listed',
  'Foreign Listed (25%)',
  False,
  None,
  None,
  '25.00',
  True,
  False,
  None,
  'Foreign shares under a tax treaty. Capital gains generally exempt. Dividends 5% with WHT '
  'credit.',
  True),
 ('Foreign Listed Shares (30% Dividend)',
  'Foreign Listed (30%)',
  False,
  None,
  None,
  '30.00',
  True,
  False,
  None,
  None,
  True),
 ('FX Spot', 'FX Spot', True, '15.00', None, None, None, None, '15.00', None, True),
 ('Local Listed',
  'Local Listed Shares',
  False,
  None,
  '659-660',
  '5.00',
  True,
  False,
  None,
  'Listed shares on local exchange. Capital gains exempt for retail (<0.5% holding). Dividends '
  'taxed at 5% with foreign WHT credit.',
  True),
 ('Non-UCITS',
  'Non-UCITS Fund / ETF',
  True,
  '15.00',
  None,
  '5.00',
  True,
  True,
  None,
  'Non-UCITS funds and leveraged/inverse ETFs. Capital gains taxed at 15%, dividends at 5%.',
  True),
 ('Other',
  'Other / Unclassified',
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  'Review manually â€” tax treatment not determined.',
  True),
 ('Spain Regulated Shares',
  'Spain Regulated',
  False,
  None,
  None,
  '15.00',
  True,
  False,
  None,
  None,
  True),
 ('UCITS',
  'UCITS EU Fund / ETF',
  False,
  None,
  None,
  '0.00',
  False,
  False,
  None,
  'EU-domiciled UCITS funds. Both capital gains and reinvested dividends are exempt.',
  True)]

# (instrument_type, tax_category_override, notes)
INSTRUMENT_TYPE_TAX_OVERRIDE = [('Bond', 'Bond', 'Always bond tax rules regardless of security'),
 ('CEF', 'Non-UCITS', 'Closed-end funds treated as Non-UCITS'),
 ('CFD', 'Non-UCITS', 'All CFDs are fully taxable'),
 ('CFDOnETF', 'Non-UCITS', 'UCITS exemption does not apply to CFD wrappers'),
 ('CFDOnFund', 'Non-UCITS', 'Fund CFDs fully taxable'),
 ('CFDOnFutures', 'Non-UCITS', 'Futures CFDs fully taxable'),
 ('CFDOnIndex', 'Non-UCITS', 'Index CFDs fully taxable'),
 ('CFDOnStock', None, "Use underlying security's Tax_Category"),
 ('ETF', None, "Use underlying security's Tax_Category"),
 ('Fund', None, "Use underlying security's Tax_Category"),
 ('FX Spot', 'FX Spot', 'Includes commodity/FX pairs traded as FX Spot on SAXO'),
 ('Option', 'Other', 'Options â€” review manually'),
 ('Other', 'Other', 'Review manually'),
 ('Stock', None, "Use underlying security's Tax_Category")]

# (ticker, name, type, currency_shortname, sector, industry, yahoo_ticker, tv_symbol,
#  tv_exchange, isin, tax_category, is_active, is_tax_exempt)
SECURITIES = [('0VQL.L',
  'iShares Gold EUR Hedged (CH) (Acc)',
  'ETF',
  'EUR',
  None,
  None,
  '0VQL.L',
  'CSGLDE.EUR',
  'SIX',
  'CH0104136319',
  'Non-UCITS',
  True,
  False),
 ('29GA.MI',
  'iShares iBonds Dec 2029 Term € Corp UCITS ETF EUR (Acc)',
  'ETF',
  'EUR',
  None,
  None,
  '29GA.MI',
  'I0C0',
  'MUN',
  'IE000SNLFDR7',
  'UCITS',
  True,
  False),
 ('30IA.MI',
  'iShares iBonds Dec 2030 Term € Corp UCITS ETF EUR (Acc)',
  'ETF',
  'EUR',
  None,
  None,
  '30IA.MI',
  'R180',
  'MUN',
  'IE000Y2BJVK9',
  'UCITS',
  True,
  False),
 ('4BRZ.DE',
  'iShares MSCI Brazil UCITS ETF (DE) USD (Acc)',
  'ETF',
  'USD',
  None,
  None,
  '4BRZ.DE',
  '4BRZ',
  'XETR',
  'DE000A0Q4R85',
  'UCITS',
  True,
  True),
 ('A',
  'Agilent Technologies, Inc.',
  'Stock',
  'USD',
  'Healthcare',
  'Diagnostics & Research',
  'A',
  'A',
  'NYSE',
  'US00846U1016',
  'Foreign Listed',
  True,
  False),
 ('AAPL',
  'Apple Inc',
  'Stock',
  'USD',
  'Technology',
  'Consumer Electronics',
  'AAPL',
  'AAPL',
  'NASDAQ',
  'US0378331005',
  'Foreign Listed',
  True,
  False),
 ('ABBV',
  'AbbVie Inc.',
  'Stock',
  'USD',
  'Healthcare',
  'Drug Manufacturers - General',
  'ABBV',
  'ABBV',
  'NYSE',
  'US00287Y1091',
  None,
  True,
  False),
 ('ABT',
  'Abbott Laboratories',
  'Stock',
  'USD',
  'Healthcare',
  'Medical Devices',
  'ABT',
  'ABT',
  'NYSE',
  'US0028241000',
  'Foreign Listed',
  True,
  False),
 ('ADBE',
  'Adobe Inc',
  'Stock',
  'USD',
  'Technology',
  'Software - Application',
  'ADBE',
  'ADBE',
  'NASDAQ',
  'US00724F1012',
  'Foreign Listed',
  True,
  False),
 ('ADC',
  'Agree Realty Corporation',
  'Stock',
  'USD',
  'Real Estate',
  'REIT - Retail',
  'ADC',
  'ADC',
  'NYSE',
  'US0084921008',
  'Foreign Listed',
  True,
  False),
 ('ADP',
  'Automatic Data Processing, Inc.',
  'Stock',
  'USD',
  'Technology',
  'Software - Application',
  'ADP',
  'ADP',
  'NASDAQ',
  'US0530151036',
  'Foreign Listed',
  True,
  False),
 ('AFL',
  'Aflac Incorporated',
  'Stock',
  'USD',
  'Financial Services',
  'Insurance - Life',
  'AFL',
  'AFL',
  'NYSE',
  'US0010551028',
  'Foreign Listed',
  True,
  False),
 ('AGNC',
  'AGNC Investment Corp.',
  'Stock',
  'USD',
  'Real Estate',
  'REIT - Mortgage',
  'AGNC',
  'AGNC',
  'NASDAQ',
  'US00123Q1040',
  'Foreign Listed Shares (30% Dividend)',
  True,
  False),
 ('AMAT',
  'Applied Materials, Inc.',
  'Stock',
  'USD',
  'Technology',
  'Semiconductor Equipment & Materials',
  'AMAT',
  'AMAT',
  'NASDAQ',
  'US0382221051',
  'Foreign Listed',
  True,
  False),
 ('AMD',
  'Advanced Micro Devices Inc',
  'Stock',
  'USD',
  'Technology',
  'Semiconductors',
  'AMD',
  'AMD',
  'NASDAQ',
  'US0079031078',
  'Foreign Listed',
  True,
  False),
 ('AMGN',
  'Amgen Inc.',
  'Stock',
  'USD',
  'Healthcare',
  'Drug Manufacturers - General',
  'AMGN',
  'AMGN',
  'NASDAQ',
  'US0311621009',
  'Foreign Listed',
  True,
  False),
 ('AMZN',
  'Amazon.com Inc',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Internet Retail',
  'AMZN',
  'AMZN',
  'NASDAQ',
  'US0231351067',
  'Foreign Listed',
  True,
  False),
 ('APE',
  'AMC Entertainment Holdings Inc - Preferred',
  'Stock',
  'USD',
  'Communication Services',
  'Entertainment',
  'AMC',
  'AMC',
  'NYSE',
  'US00165C1045',
  'Foreign Listed',
  True,
  False),
 ('ARM',
  'Arm Holdings PLC',
  'Stock',
  'USD',
  'Technology',
  'Semiconductors',
  'ARM',
  'ARM',
  'NASDAQ',
  'US0420682058',
  'Foreign Listed',
  True,
  False),
 ('AU',
  'AngloGold Ashanti plc',
  'Stock',
  'USD',
  'Basic Materials',
  'Gold',
  'AU',
  'AU',
  'NYSE',
  'GB00BRXH2664',
  'Foreign Listed',
  True,
  False),
 ('AVGO',
  'Broadcom Inc.',
  'Stock',
  'USD',
  'Technology',
  'Semiconductors',
  'AVGO',
  'AVGO',
  'NASDAQ',
  'CA11134P1009',
  'Foreign Listed',
  True,
  False),
 ('AWK',
  'American Water Works Company, Inc.',
  'Stock',
  'USD',
  'Utilities',
  'Utilities - Regulated Water',
  'AWK',
  'AWK',
  'NYSE',
  'US0304201033',
  'Foreign Listed Shares (30% Dividend)',
  True,
  False),
 ('BA',
  'Boeing Co',
  'Stock',
  'USD',
  'Industrials',
  'Aerospace & Defense',
  'BA',
  'BA',
  'NYSE',
  'US0970231058',
  'Foreign Listed',
  True,
  False),
 ('BABA',
  'Alibaba Group Holding Ltd',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Internet Retail',
  'BABA',
  'BABA',
  'NYSE',
  'US01609W1027',
  'Foreign Listed',
  True,
  False),
 ('BLK',
  'BlackRock Inc',
  'Stock',
  'USD',
  'Financial Services',
  'Asset Management',
  'BLK',
  'BLK',
  'NYSE',
  'US09290D1019',
  'Foreign Listed',
  True,
  False),
 ('BMO',
  'Bank of Montreal',
  'Stock',
  'USD',
  'Financial Services',
  'Banks - Diversified',
  'BMO',
  'BMO',
  'NYSE',
  'CA0636711016',
  'Foreign Listed',
  True,
  False),
 ('BMY',
  'Bristol-Myers Squibb Company',
  'Stock',
  'USD',
  'Healthcare',
  'Drug Manufacturers - General',
  'BMY',
  'BMY',
  'NYSE',
  'US1101221083',
  'Foreign Listed',
  True,
  False),
 ('BNS',
  'The Bank of Nova Scotia',
  'Stock',
  'USD',
  'Financial Services',
  'Banks - Diversified',
  'BNS',
  'BNS',
  'NYSE',
  'CA0641491075',
  'Foreign Listed',
  True,
  False),
 ('BR',
  'Broadridge Financial Solutions, Inc.',
  'Stock',
  'USD',
  'Technology',
  'Information Technology Services',
  'BR',
  'BR',
  'NYSE',
  'US11133T1034',
  'Foreign Listed',
  True,
  False),
 ('BRK.B',
  'Berkshire Hathaway Inc',
  'Stock',
  'USD',
  'Financial Services',
  'Insurance - Diversified',
  'BRK-B',
  'BRK.B',
  'NYSE',
  'US0846707026',
  'Foreign Listed',
  True,
  False),
 ('BTI',
  'British American Tobacco p.l.c. (USD)',
  'Stock',
  'USD',
  'Consumer Defensive',
  'Tobacco',
  'BTI',
  'BTI',
  'NYSE',
  'US1104481072',
  'Foreign Listed',
  True,
  False),
 ('BWXT',
  'BWX Technologies, Inc.',
  'Stock',
  'USD',
  'Industrials',
  'Aerospace & Defense',
  'BWXT',
  'BWXT',
  'NYSE',
  'US05605H1005',
  'Foreign Listed',
  True,
  False),
 ('C',
  'Citigroup Inc.',
  'Stock',
  'USD',
  'Financial Services',
  'Banks - Diversified',
  'C',
  'C',
  'NYSE',
  'US1729674242',
  'Foreign Listed',
  True,
  False),
 ('CAH',
  'Cardinal Health, Inc.',
  'Stock',
  'USD',
  'Healthcare',
  'Medical Distribution',
  'CAH',
  'CAH',
  'NYSE',
  'US14149Y1082',
  'Foreign Listed',
  True,
  False),
 ('CB',
  'Chubb Limited',
  'Stock',
  'USD',
  'Financial Services',
  'Insurance - Property & Casualty',
  'CB',
  'CB',
  'NYSE',
  'CH0044328745',
  'Foreign Listed',
  True,
  False),
 ('CEG',
  'Constellation Energy Corporation',
  'Stock',
  'USD',
  'Utilities',
  'Utilities - Independent Power Producers',
  'CEG',
  'CEG',
  'NASDAQ',
  'US21037T1097',
  'Foreign Listed',
  True,
  False),
 ('CF',
  'CF Industries Holdings, Inc.',
  'Stock',
  'USD',
  'Basic Materials',
  'Agricultural Inputs',
  'CF',
  'CF',
  'NYSE',
  'US1252691001',
  'Foreign Listed',
  True,
  False),
 ('CLX',
  'The Clorox Company',
  'Stock',
  'USD',
  'Consumer Defensive',
  'Household & Personal Products',
  'CLX',
  'CLX',
  'NYSE',
  'US1890541097',
  'Foreign Listed',
  True,
  False),
 ('CNQ',
  'Canadian Natural Resources Limited',
  'Stock',
  'USD',
  'Energy',
  'Oil & Gas E&P',
  'CNQ',
  'CNQ',
  'NYSE',
  'CA1363851017',
  'Foreign Listed',
  True,
  False),
 ('CNYA.L',
  'iShares MSCI China A UCITS ETF USD (Acc)',
  'ETF',
  'USD',
  None,
  None,
  'CNYA.L',
  'CNYA',
  'LSE',
  'IE00BQT3WG13',
  'UCITS',
  True,
  True),
 ('COST',
  'Costco Wholesale Corporation',
  'Stock',
  'USD',
  'Consumer Defensive',
  'Discount Stores',
  'COST',
  'COST',
  'NASDAQ',
  'US22160K1051',
  'Foreign Listed',
  True,
  False),
 ('CPB',
  "The Campbell's Company",
  'Stock',
  'USD',
  'Consumer Defensive',
  'Packaged Foods',
  'CPB',
  'CPB',
  'NASDAQ',
  'US1344291091',
  'Foreign Listed',
  True,
  False),
 ('CSCO',
  'Cisco Systems, Inc.',
  'Stock',
  'USD',
  'Technology',
  'Communication Equipment',
  'CSCO',
  'CSCO',
  'NASDAQ',
  'US17275R1023',
  'Foreign Listed',
  True,
  False),
 ('CSGP',
  'CoStar Group, Inc.',
  'Stock',
  'USD',
  'Real Estate',
  'Real Estate Services',
  'CSGP',
  'CSGP',
  'NASDAQ',
  'US22160N1090',
  'Foreign Listed',
  True,
  False),
 ('CVX',
  'Chevron Corporation',
  'Stock',
  'USD',
  'Energy',
  'Oil & Gas Integrated',
  'CVX',
  'CVX',
  'NYSE',
  'ARDEUT110087',
  'Foreign Listed',
  True,
  False),
 ('DELL',
  'Dell Technologies Inc.',
  'Stock',
  'USD',
  'Technology',
  'Computer Hardware',
  'DELL',
  'DELL',
  'NYSE',
  'US24703L2025',
  'Foreign Listed',
  True,
  False),
 ('DIS',
  'The Walt Disney Company',
  'Stock',
  'USD',
  'Communication Services',
  'Entertainment',
  'DIS',
  'DIS',
  'NYSE',
  'US2546871060',
  'Foreign Listed',
  True,
  False),
 ('DKNG',
  'DraftKings Inc.',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Gambling',
  'DKNG',
  'DKNG',
  'NASDAQ',
  'US26142V1052',
  'Foreign Listed Shares (30% Dividend)',
  True,
  False),
 ('DUK',
  'Duke Energy Corporation',
  'Stock',
  'USD',
  'Utilities',
  'Utilities - Regulated Electric',
  'DUK',
  'DUK',
  'NYSE',
  'US26441C2044',
  'Foreign Listed',
  True,
  False),
 ('EBAY',
  'eBay Inc',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Internet Retail',
  'EBAY',
  'EBAY',
  'NASDAQ',
  'US2786421030',
  'Foreign Listed',
  True,
  False),
 ('ECL',
  'Ecolab Inc.',
  'Stock',
  'USD',
  'Basic Materials',
  'Specialty Chemicals',
  'ECL',
  'ECL',
  'NYSE',
  'US2788651006',
  'Foreign Listed',
  True,
  False),
 ('EFX',
  'Equifax Inc.',
  'Stock',
  'USD',
  'Industrials',
  'Consulting Services',
  'EFX',
  'EFX',
  'NYSE',
  'US2944291051',
  'Foreign Listed',
  True,
  False),
 ('EMR',
  'Emerson Electric Co.',
  'Stock',
  'USD',
  'Industrials',
  'Specialty Industrial Machinery',
  'EMR',
  'EMR',
  'NYSE',
  'US2910111044',
  'Foreign Listed',
  True,
  False),
 ('EUNA.DE',
  'iShares Core Global Aggregate Bond UCITS ETF EUR Hedged (Acc)',
  'ETF',
  'EUR',
  'Fixed Income',
  'Multi-sector bonds',
  'EUNA.DE',
  'EUNA',
  'XETR',
  'IE00BDBRDM35',
  'UCITS',
  True,
  True),
 ('EUNK.DE',
  'iShares Core MSCI Europe UCITS ETF EUR (Acc)',
  'ETF',
  'EUR',
  'Equity',
  'Broad market',
  'EUNK.DE',
  'EUNK',
  'XETR',
  'IE00B4K48X80',
  'UCITS',
  True,
  True),
 ('EUNL.DE',
  'iShares Core MSCI World UCITS ETF USD (Acc)',
  'ETF',
  'EUR',
  'Equity',
  'Broad market',
  'EUNL.DE',
  'EUNL',
  'SWB',
  'IE00B4L5Y983',
  'UCITS',
  True,
  True),
 ('EUNM.DE',
  'iShares MSCI EM UCITS ETF USD (Acc)',
  'ETF',
  'EUR',
  'Equity',
  'Broad market',
  'EUNM.DE',
  'EUNM',
  'FWB',
  'IE00B4L5YC18',
  'UCITS',
  True,
  True),
 ('EUNU.DE',
  'iShares Core Global Aggregate Bond UCITS ETF USD (Dist)',
  'ETF',
  'EUR',
  'Fixed Income',
  'Multi-sector bonds',
  'EUNU.DE',
  'EUNU',
  'XETR',
  'IE00B3F81409',
  'UCITS',
  True,
  True),
 ('EXH9.DE',
  'iShares STOXX Europe 600 Utilities UCITS ETF (Dist)',
  'ETF',
  'EUR',
  None,
  None,
  'EXH9.DE',
  'EXH9',
  'XETR',
  'DE000A0Q4R02',
  'UCITS',
  True,
  True),
 ('EZU',
  'iShares MSCI Eurozone ETF USD (Dist)',
  'ETF',
  'USD',
  'Equity',
  'Broad market',
  'EZU',
  'EZU',
  'CBOE',
  'US4642866085',
  'UCITS',
  True,
  False),
 ('FERG',
  'Ferguson Enterprises Inc.',
  'Stock',
  'USD',
  'Industrials',
  'Industrial Distribution',
  'FERG',
  'FERG',
  'NYSE',
  'US31488V1070',
  'Foreign Listed',
  True,
  False),
 ('FISV',
  'Fiserv Inc',
  'Stock',
  'USD',
  'Technology',
  'Software - Application',
  'FISV',
  'FISV',
  'NASDAQ',
  'US3377381088',
  'Foreign Listed',
  True,
  False),
 ('FLEX',
  'Flex Ltd.',
  'Stock',
  'USD',
  'Technology',
  'Electronic Components',
  'FLEX',
  'FLEX',
  'NASDAQ',
  'SG9999000020',
  'Foreign Listed',
  True,
  False),
 ('FLUT',
  'Flutter Entertainment plc',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Gambling',
  'FLUT',
  'FLUT',
  'NYSE',
  'IE00BWT6H894',
  'Foreign Listed Shares (30% Dividend)',
  True,
  False),
 ('GD',
  'General Dynamics Corporation',
  'Stock',
  'USD',
  'Industrials',
  'Aerospace & Defense',
  'GD',
  'GD',
  'NYSE',
  'US3695501086',
  'Foreign Listed',
  True,
  False),
 ('GFI',
  'Gold Fields Limited',
  'Stock',
  'USD',
  'Basic Materials',
  'Gold',
  'GFI',
  'GFI',
  'NYSE',
  'US38059T1060',
  'Foreign Listed',
  True,
  False),
 ('GILD',
  'Gilead Sciences, Inc.',
  'Stock',
  'USD',
  'Healthcare',
  'Drug Manufacturers - General',
  'GILD',
  'GILD',
  'NASDAQ',
  'US3755581036',
  'Foreign Listed',
  True,
  False),
 ('GLW',
  'Corning Incorporated',
  'Stock',
  'USD',
  'Technology',
  'Electronic Components',
  'GLW',
  'GLW',
  'NYSE',
  'US2193501051',
  'Foreign Listed',
  True,
  False),
 ('GM',
  'General Motors Co',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Auto Manufacturers',
  'GM',
  'GM',
  'NYSE',
  'US37045V1008',
  'Foreign Listed',
  True,
  False),
 ('GME',
  'GameStop Corp',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Specialty Retail',
  'GME',
  'GME',
  'NYSE',
  'US36467W1099',
  'Foreign Listed',
  True,
  False),
 ('GOOD',
  'Gladstone Commercial Corporation',
  'Stock',
  'USD',
  'Real Estate',
  'REIT - Diversified',
  'GOOD',
  'GOOD',
  'NASDAQ',
  'US3765361080',
  'Foreign Listed',
  True,
  False),
 ('GOOG',
  'Alphabet Inc. (Class C)',
  'Stock',
  'USD',
  'Communication Services',
  'Internet Content & Information',
  'GOOG',
  'GOOG',
  'NASDAQ',
  'US02079K1079',
  'Foreign Listed',
  True,
  False),
 ('GOOGL',
  'Alphabet Inc (Class A)',
  'Stock',
  'USD',
  'Communication Services',
  'Internet Content & Information',
  'GOOGL',
  'GOOGL',
  'NASDAQ',
  'US02079K3059',
  'Foreign Listed',
  True,
  False),
 ('GWW',
  'W.W. Grainger, Inc.',
  'Stock',
  'USD',
  'Industrials',
  'Industrial Distribution',
  'GWW',
  'GWW',
  'NYSE',
  'US3848021040',
  'Foreign Listed',
  True,
  False),
 ('IAU',
  'iShares Gold Trust ETF USD (Dist)',
  'ETF',
  'USD',
  None,
  None,
  'IAU',
  'IAU',
  'AMEX',
  'US4642852044',
  'Non-UCITS',
  True,
  False),
 ('IBCI',
  'iShares Euro Inflation Linked Govt Bond UCITS ETF EUR (Acc)',
  'ETF',
  'EUR',
  None,
  None,
  'IBCI.DE',
  'IBCI',
  'EURONEXT',
  'IE00B0M62X26',
  'UCITS',
  True,
  True),
 ('IBGS.MI',
  'iShares € Govt Bond 1-3yr UCITS ETF EUR (Dist)',
  'ETF',
  'EUR',
  None,
  None,
  'IBGS.MI',
  'IBGS-ETFP',
  'EURONEXT',
  'IE00B14X4Q57',
  'UCITS',
  True,
  True),
 ('IBM',
  'International Business Machines Corporation',
  'Stock',
  'USD',
  'Technology',
  'Information Technology Services',
  'IBM',
  'IBM',
  'NYSE',
  'US4592001014',
  'Foreign Listed',
  True,
  False),
 ('IDXX',
  'IDEXX Laboratories, Inc.',
  'Stock',
  'USD',
  'Healthcare',
  'Diagnostics & Research',
  'IDXX',
  'IDXX',
  'NASDAQ',
  'US45168D1046',
  'Foreign Listed',
  True,
  False),
 ('IEAC.MI',
  'iShares Core € Corp Bond UCITS ETF EUR (Dist)',
  'ETF',
  'EUR',
  None,
  None,
  'IEAC.MI',
  'IEAC-ETFP',
  'EURONEXT',
  'IE00B3F81R35',
  'UCITS',
  True,
  True),
 ('INTC',
  'Intel Corp',
  'Stock',
  'USD',
  'Technology',
  'Semiconductors',
  'INTC',
  'INTC',
  'NASDAQ',
  'US4581401001',
  'Foreign Listed',
  True,
  False),
 ('IONQ',
  'IonQ, Inc.',
  'Stock',
  'USD',
  'Technology',
  'Computer Hardware',
  'IONQ',
  'IONQ',
  'NYSE',
  'US46222L1089',
  'Foreign Listed',
  True,
  False),
 ('IQQ0.DE',
  'iShares Edge MSCI World Minimum Volatility UCITS ETF USD (Acc)',
  'ETF',
  'EUR',
  None,
  None,
  'IQQ0.DE',
  'IQQ0',
  'XETR',
  'IE00B8FHGS14',
  'UCITS',
  True,
  True),
 ('IQQA.DE',
  'iShares Euro Dividend UCITS ETF EUR (Dist)',
  'ETF',
  'EUR',
  None,
  None,
  'IQQA.DE',
  'IQQA',
  'XETR',
  'IE00B0M62S72',
  'UCITS',
  True,
  True),
 ('IQQQ.DE',
  'iShares Global Water UCITS ETF USD (Dist)',
  'ETF',
  'EUR',
  'Equity',
  'Utilities',
  'IQQQ.DE',
  'IQQQ',
  'XETR',
  'IE00B1TXK627',
  'UCITS',
  True,
  True),
 ('IS0E.DE',
  'iShares Gold Producers UCITS ETF USD (Acc)',
  'ETF',
  'EUR',
  'Equity',
  'Materials',
  'IS0E.DE',
  'IS0E',
  'FWB',
  'IE00B6R52036',
  'UCITS',
  True,
  True),
 ('ISRG',
  'Intuitive Surgical, Inc.',
  'Stock',
  'USD',
  'Healthcare',
  'Medical Instruments & Supplies',
  'ISRG',
  'ISRG',
  'NASDAQ',
  'US46120E6023',
  'Foreign Listed',
  True,
  False),
 ('ITUB',
  'Itau Unibanco Holding SA',
  'Stock',
  'USD',
  'Financial Services',
  'Banks - Regional',
  'ITUB',
  'ITUB',
  'NYSE',
  'US4655621062',
  'Foreign Listed',
  True,
  False),
 ('ITW',
  'Illinois Tool Works Inc.',
  'Stock',
  'USD',
  'Industrials',
  'Specialty Industrial Machinery',
  'ITW',
  'ITW',
  'NYSE',
  'US4523081093',
  'Foreign Listed',
  True,
  False),
 ('IUHE.AS',
  'iShares S&P 500 Health Care Sector UCITS ETF EUR Hedged (Dist)',
  'ETF',
  'EUR',
  None,
  None,
  'IUHE.AS',
  'IUHE',
  'EURONEXT',
  'IE00BMBKBZ46',
  'UCITS',
  True,
  True),
 ('IUSQ.DE',
  'iShares MSCI ACWI UCITS ETF USD (Acc)',
  'ETF',
  'EUR',
  'Equity',
  'Broad market',
  'IUSQ.DE',
  'IUSQ',
  'XETR',
  'IE00B6R52259',
  'UCITS',
  True,
  True),
 ('JNJ',
  'Johnson & Johnson',
  'Stock',
  'USD',
  'Healthcare',
  'Drug Manufacturers - General',
  'JNJ',
  'JNJ',
  'NYSE',
  'US4781601046',
  'Foreign Listed',
  True,
  False),
 ('JPM',
  'JPMorgan Chase & Co.',
  'Stock',
  'USD',
  'Financial Services',
  'Banks - Diversified',
  'JPM',
  'JPM',
  'NYSE',
  'US46625H1005',
  'Foreign Listed',
  True,
  False),
 ('KLAC',
  'KLA Corporation',
  'Stock',
  'USD',
  'Technology',
  'Semiconductor Equipment & Materials',
  'KLAC',
  'KLAC',
  'NASDAQ',
  'US4824801009',
  'Foreign Listed',
  True,
  False),
 ('KMB',
  'Kimberly-Clark Corporation',
  'Stock',
  'USD',
  'Consumer Defensive',
  'Household & Personal Products',
  'KMB',
  'KMB',
  'NASDAQ',
  'US4943681035',
  'Foreign Listed',
  True,
  False),
 ('KO',
  'The Coca-Cola Company',
  'Stock',
  'USD',
  'Consumer Defensive',
  'Beverages - Non-Alcoholic',
  'KO',
  'KO',
  'NYSE',
  'US1912161007',
  'Foreign Listed',
  True,
  False),
 ('LLY',
  'Eli Lilly and Company',
  'Stock',
  'USD',
  'Healthcare',
  'Drug Manufacturers - General',
  'LLY',
  'LLY',
  'NYSE',
  'US5324571083',
  'Foreign Listed',
  True,
  False),
 ('LOW',
  "Lowe's Companies, Inc.",
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Home Improvement Retail',
  'LOW',
  'LOW',
  'NYSE',
  'US5486611073',
  'Foreign Listed',
  True,
  False),
 ('LTC',
  'LTC Properties, Inc.',
  'Stock',
  'USD',
  'Real Estate',
  'REIT - Healthcare Facilities',
  'LTC',
  'LTC',
  'NYSE',
  'US5021751020',
  'Foreign Listed',
  True,
  False),
 ('MA',
  'Mastercard Inc',
  'Stock',
  'USD',
  'Financial Services',
  'Credit Services',
  'MA',
  'MA',
  'NYSE',
  'US57636Q1040',
  'Foreign Listed',
  True,
  False),
 ('MAIN',
  'Main Street Capital Corporation',
  'Stock',
  'USD',
  'Financial Services',
  'Asset Management',
  'MAIN',
  'MAIN',
  'NYSE',
  'US56035L1044',
  'Foreign Listed',
  True,
  False),
 ('MCD',
  "McDonald's Corporation",
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Restaurants',
  'MCD',
  'MCD',
  'NYSE',
  'US5801351017',
  'Foreign Listed',
  True,
  False),
 ('MET',
  'MetLife Inc',
  'Stock',
  'USD',
  'Financial Services',
  'Insurance - Life',
  'MET',
  'MET',
  'NYSE',
  'US59156R1086',
  'Foreign Listed',
  True,
  False),
 ('META',
  'Meta Platforms Inc',
  'Stock',
  'USD',
  'Communication Services',
  'Internet Content & Information',
  'META',
  'META',
  'NASDAQ',
  'US30303M1027',
  'Foreign Listed',
  True,
  False),
 ('MPWR',
  'Monolithic Power Systems, Inc.',
  'Stock',
  'USD',
  'Technology',
  'Semiconductors',
  'MPWR',
  'MPWR',
  'NASDAQ',
  'US6098391054',
  'Foreign Listed',
  True,
  False),
 ('MRK',
  'Merck & Co Inc',
  'Stock',
  'USD',
  'Healthcare',
  'Drug Manufacturers - General',
  'MRK',
  'MRK',
  'NYSE',
  'US58933Y1055',
  'Foreign Listed',
  True,
  False),
 ('MRVL',
  'Marvell Technology, Inc.',
  'Stock',
  'USD',
  'Technology',
  'Semiconductors',
  'MRVL',
  'MRVL',
  'NASDAQ',
  'US5738741041',
  'Foreign Listed',
  True,
  False),
 ('MSFT',
  'Microsoft Corp',
  'Stock',
  'USD',
  'Technology',
  'Software - Infrastructure',
  'MSFT',
  'MSFT',
  'NASDAQ',
  'US5949181045',
  'Foreign Listed',
  True,
  False),
 ('MU',
  'Micron Technology, Inc.',
  'Stock',
  'USD',
  'Technology',
  'Semiconductors',
  'MU',
  'MU',
  'NASDAQ',
  'US5951121038',
  'Foreign Listed',
  True,
  False),
 ('NEM',
  'Newmont Corporation',
  'Stock',
  'USD',
  'Basic Materials',
  'Gold',
  'NEM',
  'NEM',
  'NYSE',
  'US6516391066',
  'Foreign Listed',
  True,
  False),
 ('NFLX',
  'Netflix Inc',
  'Stock',
  'USD',
  'Communication Services',
  'Entertainment',
  'NFLX',
  'NFLX',
  'NASDAQ',
  'US64110L1061',
  'Foreign Listed',
  True,
  False),
 ('NIO',
  'NIO Inc.',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Auto Manufacturers',
  'NIO',
  'NIO',
  'NYSE',
  'US62914V1061',
  'Foreign Listed',
  True,
  False),
 ('NKE',
  'Nike Inc',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Footwear & Accessories',
  'NKE',
  'NKE',
  'NYSE',
  'US6541061031',
  'Foreign Listed',
  True,
  False),
 ('NLR',
  'VanEck Uranium and Nuclear ETF (Dis)',
  'ETF',
  'USD',
  'Equity',
  'Energy',
  'NLR',
  'NLR',
  'AMEX',
  'US92189F6016',
  'Non-UCITS',
  True,
  False),
 ('NUE',
  'Nucor Corporation',
  'Stock',
  'USD',
  'Basic Materials',
  'Steel',
  'NUE',
  'NUE',
  'NYSE',
  'US6703461052',
  'Foreign Listed',
  True,
  False),
 ('NVDA',
  'NVIDIA Corp',
  'Stock',
  'USD',
  'Technology',
  'Semiconductors',
  'NVDA',
  'NVDA',
  'NASDAQ',
  'US67066G1040',
  'Foreign Listed Shares (30% Dividend)',
  True,
  False),
 ('O',
  'Realty Income Corporation',
  'Stock',
  'USD',
  'Real Estate',
  'REIT - Retail',
  'O',
  'O',
  'NYSE',
  'US7561091049',
  'Foreign Listed',
  True,
  False),
 ('OKLO',
  'Oklo Inc. (Class A)',
  'Stock',
  'USD',
  'Utilities',
  'Utilities - Independent Power Producers',
  'OKLO',
  'OKLO',
  'NYSE',
  'US02156V1098',
  'Foreign Listed',
  True,
  False),
 ('ORCL',
  'Oracle Corporation',
  'Stock',
  'USD',
  'Technology',
  'Software - Infrastructure',
  'ORCL',
  'ORCL',
  'NYSE',
  'US68389X1054',
  'Foreign Listed',
  True,
  False),
 ('OTLY',
  'Oatly Group AB (publ)',
  'Stock',
  'USD',
  'Consumer Defensive',
  'Packaged Foods',
  'OTLY',
  'OTLY',
  'NASDAQ',
  'US67421J2078',
  'Foreign Listed',
  True,
  False),
 ('PEG',
  'Public Service Enterprise Group Incorporated',
  'Stock',
  'USD',
  'Utilities',
  'Utilities - Regulated Electric',
  'PEG',
  'PEG',
  'NYSE',
  'US7445731067',
  'Foreign Listed',
  True,
  False),
 ('PEP',
  'PepsiCo, Inc.',
  'Stock',
  'USD',
  'Consumer Defensive',
  'Beverages - Non-Alcoholic',
  'PEP',
  'PEP',
  'NASDAQ',
  'US7134481081',
  'Foreign Listed',
  True,
  False),
 ('PG',
  'The Procter & Gamble Company',
  'Stock',
  'USD',
  'Consumer Defensive',
  'Household & Personal Products',
  'PG',
  'PG',
  'NYSE',
  'US7427181091',
  'Foreign Listed',
  True,
  False),
 ('PHO',
  'Invesco Water Resources ETF (Dis)',
  'ETF',
  'USD',
  None,
  None,
  'PHO',
  'PHO',
  'NASDAQ',
  'US46137V1420',
  'Non-UCITS',
  True,
  False),
 ('PLTR',
  'Palantir Technologies Inc.',
  'Stock',
  'USD',
  'Technology',
  'Software - Infrastructure',
  'PLTR',
  'PLTR',
  'NASDAQ',
  'US69608A1088',
  'Foreign Listed',
  True,
  False),
 ('PNR',
  'Pentair plc',
  'Stock',
  'USD',
  'Industrials',
  'Specialty Industrial Machinery',
  'PNR',
  'PNR',
  'NYSE',
  'IE00BLS09M33',
  'Foreign Listed',
  True,
  False),
 ('PPFD',
  'iShares Physical Silver ETC (Acc)',
  'ETF',
  'EUR',
  None,
  None,
  'PPFD.SG',
  'PPFD',
  'HAM',
  'IE00B4NCWG09',
  'Non-UCITS',
  True,
  False),
 ('PPG',
  'PPG Industries, Inc.',
  'Stock',
  'USD',
  'Basic Materials',
  'Specialty Chemicals',
  'PPG',
  'PPG',
  'NYSE',
  'US6935061076',
  'Foreign Listed',
  True,
  False),
 ('PSKY',
  'Paramount Skydance Corporation',
  'Stock',
  'USD',
  'Communication Services',
  'Entertainment',
  'PSKY',
  'PSKY',
  'NASDAQ',
  'US69932A2042',
  None,
  True,
  False),
 ('PYPL',
  'PayPal Holdings Inc',
  'Stock',
  'USD',
  'Financial Services',
  'Credit Services',
  'PYPL',
  'PYPL',
  'NASDAQ',
  'US70450Y1038',
  'Foreign Listed',
  True,
  False),
 ('QCOM',
  'QUALCOMM Incorporated',
  'Stock',
  'USD',
  'Technology',
  'Semiconductors',
  'QCOM',
  'QCOM',
  'NASDAQ',
  'US7475251036',
  'Foreign Listed',
  True,
  False),
 ('RGLD',
  'Royal Gold, Inc.',
  'Stock',
  'USD',
  'Basic Materials',
  'Gold',
  'RGLD',
  'RGLD',
  'NASDAQ',
  'US7802871084',
  'Foreign Listed',
  True,
  False),
 ('RKLB',
  'Rocket Lab Corporation',
  'Stock',
  'USD',
  'Industrials',
  'Aerospace & Defense',
  'RKLB',
  'RKLB',
  'NASDAQ',
  'US7731211089',
  'Foreign Listed',
  True,
  False),
 ('ROP',
  'Roper Technologies, Inc.',
  'Stock',
  'USD',
  'Technology',
  'Software - Application',
  'ROP',
  'ROP',
  'NASDAQ',
  'US7766961061',
  'Foreign Listed',
  True,
  False),
 ('RY',
  'Royal Bank of Canada',
  'Stock',
  'USD',
  'Financial Services',
  'Banks - Diversified',
  'RY',
  'RY',
  'NYSE',
  'CA7800871021',
  'Foreign Listed',
  True,
  False),
 ('SBUX',
  'Starbucks Corporation',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Restaurants',
  'SBUX',
  'SBUX',
  'NASDAQ',
  'US8552441094',
  'Foreign Listed',
  True,
  False),
 ('SHW',
  'The Sherwin-Williams Company',
  'Stock',
  'USD',
  'Basic Materials',
  'Specialty Chemicals',
  'SHW',
  'SHW',
  'NYSE',
  'US8243481061',
  'Foreign Listed',
  True,
  False),
 ('SIRI',
  'Sirius XM Holdings Inc',
  'Stock',
  'USD',
  'Communication Services',
  'Entertainment',
  'SIRI',
  'SIRI',
  'NASDAQ',
  'US8299331004',
  'Foreign Listed',
  True,
  False),
 ('SLB',
  'SLB N.V.',
  'Stock',
  'USD',
  'Energy',
  'Oil & Gas Equipment & Services',
  'SLB',
  'SLB',
  'NYSE',
  'AN8068571086',
  'Foreign Listed',
  True,
  False),
 ('SLV',
  'iShares Silver Trust ETF USD (Dist)',
  'ETF',
  'USD',
  None,
  None,
  'SLV',
  'SLV',
  'AMEX',
  'US46428Q1094',
  'Non-UCITS',
  True,
  False),
 ('SMR',
  'NuScale Power Corporation (Class A)',
  'Stock',
  'USD',
  'Industrials',
  'Specialty Industrial Machinery',
  'SMR',
  'SMR',
  'NYSE',
  'US67079K1007',
  'Foreign Listed',
  True,
  False),
 ('SNDK',
  'Sandisk Corporation',
  'Stock',
  'USD',
  'Technology',
  'Computer Hardware',
  'SNDK',
  'SNDK',
  'NASDAQ',
  'CA8000541083',
  'Foreign Listed',
  True,
  False),
 ('SOFI',
  'SoFi Technologies, Inc.',
  'Stock',
  'USD',
  'Financial Services',
  'Credit Services',
  'SOFI',
  'SOFI',
  'NASDAQ',
  'US83406F1021',
  'Foreign Listed',
  True,
  False),
 ('SONY',
  'Sony Group Corporation',
  'Stock',
  'USD',
  'Technology',
  'Consumer Electronics',
  'SONY',
  'SONY',
  'NYSE',
  'US8356993076',
  'Foreign Listed',
  True,
  False),
 ('SPCX',
  'Space Exploration Technologies Corp.',
  'Stock',
  'USD',
  'Industrials',
  'Aerospace & Defense',
  'SPCX',
  'SPCX',
  'NASDAQ',
  'CA8459291081',
  'Foreign Listed',
  True,
  False),
 ('STX',
  'Seagate Technology Holdings plc',
  'Stock',
  'USD',
  'Technology',
  'Computer Hardware',
  'STX',
  'STX',
  'NASDAQ',
  'IE00BKVD2N49',
  'Foreign Listed',
  True,
  False),
 ('SXRS.DE',
  'iShares Diversified Commodity Swap UCITS ETF USD (Acc)',
  'ETF',
  'EUR',
  'Total Return Swap',
  'Materials',
  'SXRS.DE',
  'SXRS',
  'XETR',
  'IE00BDFL4P12',
  'UCITS',
  True,
  True),
 ('SYY',
  'Sysco Corporation',
  'Stock',
  'USD',
  'Consumer Defensive',
  'Food Distribution',
  'SYY',
  'SYY',
  'NYSE',
  'US8718291078',
  'Foreign Listed',
  True,
  False),
 ('TD',
  'The Toronto-Dominion Bank',
  'Stock',
  'USD',
  'Financial Services',
  'Banks - Diversified',
  'TD',
  'TD',
  'NYSE',
  'CA8911605092',
  'Foreign Listed',
  True,
  False),
 ('TMO',
  'Thermo Fisher Scientific Inc.',
  'Stock',
  'USD',
  'Healthcare',
  'Diagnostics & Research',
  'TMO',
  'TMO',
  'NYSE',
  'US8835561023',
  'Foreign Listed',
  True,
  False),
 ('TRI',
  'Thomson Reuters Corp (USD)',
  'Stock',
  'USD',
  'Industrials',
  'Specialty Business Services',
  'TRI',
  'TRI',
  'NASDAQ',
  'CA8849038812',
  'Foreign Listed',
  True,
  False),
 ('TROW',
  'T. Rowe Price Group, Inc.',
  'Stock',
  'USD',
  'Financial Services',
  'Asset Management',
  'TROW',
  'TROW',
  'NASDAQ',
  'US74144T1088',
  'Foreign Listed',
  True,
  False),
 ('TSLA',
  'Tesla Inc',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Auto Manufacturers',
  'TSLA',
  'TSLA',
  'NASDAQ',
  'US88160R1014',
  'Foreign Listed',
  True,
  False),
 ('TSM',
  'Taiwan Semiconductor Manufacturing Company Limited (USD)',
  'Stock',
  'USD',
  'Technology',
  'Semiconductors',
  'TSM',
  'TSM',
  'NYSE',
  'US8740391003',
  'Foreign Listed',
  True,
  False),
 ('TTWO',
  'Take-Two Interactive Software, Inc.',
  'Stock',
  'USD',
  'Communication Services',
  'Electronic Gaming & Multimedia',
  'TTWO',
  'TTWO',
  'NASDAQ',
  'US8740541094',
  'Foreign Listed',
  True,
  False),
 ('TXN',
  'Texas Instruments Incorporated',
  'Stock',
  'USD',
  'Technology',
  'Semiconductors',
  'TXN',
  'TXN',
  'NASDAQ',
  'US8825081040',
  'Foreign Listed',
  True,
  False),
 ('UEC',
  'Uranium Energy Corp.',
  'Stock',
  'USD',
  'Energy',
  'Uranium',
  'UEC',
  'UEC',
  'AMEX',
  'US9168961038',
  'Foreign Listed',
  True,
  False),
 ('UNH',
  'UnitedHealth Group Incorporated',
  'Stock',
  'USD',
  'Healthcare',
  'Healthcare Plans',
  'UNH',
  'UNH',
  'NYSE',
  'US91324P1021',
  'Foreign Listed',
  True,
  False),
 ('V',
  'Visa Inc',
  'Stock',
  'USD',
  'Financial Services',
  'Credit Services',
  'V',
  'V',
  'NYSE',
  'US92826C8394',
  'Foreign Listed',
  True,
  False),
 ('VECA.DE',
  'Vanguard EUR Corporate Bond UCITS ETF EUR (Acc)',
  'ETF',
  'EUR',
  None,
  None,
  'VECA.DE',
  'VECA',
  'XETR',
  'IE00BGYWT403',
  'UCITS',
  True,
  True),
 ('VLTO',
  'Veralto Corporation',
  'Stock',
  'USD',
  'Industrials',
  'Pollution & Treatment Controls',
  'VLTO',
  'VLTO',
  'NYSE',
  'US92338C1036',
  'Foreign Listed Shares (30% Dividend)',
  True,
  False),
 ('VUAA.DE',
  'Vanguard S&P 500 UCITS ETF USD (Acc)',
  'ETF',
  'EUR',
  'Equity',
  'Broad market',
  'VUAA.DE',
  'VUAA',
  'GETTEX',
  'IE00BFMXXD54',
  'UCITS',
  True,
  True),
 ('VWCE.DE',
  'Vanguard FTSE All-World UCITS ETF USD (Acc)',
  'ETF',
  'EUR',
  'Equity',
  'Broad market',
  'VWCE.DE',
  'VWCE',
  'TRADEGATE',
  'IE00BK5BQT80',
  'UCITS',
  True,
  True),
 ('WAB',
  'Westinghouse Air Brake Technologies Corporation',
  'Stock',
  'USD',
  'Industrials',
  'Railroads',
  'WAB',
  'WAB',
  'NYSE',
  'US9297401088',
  'Foreign Listed',
  True,
  False),
 ('WAT',
  'Waters Corporation',
  'Stock',
  'USD',
  'Healthcare',
  'Diagnostics & Research',
  'WAT',
  'WAT',
  'NYSE',
  'US9418481035',
  'Foreign Listed',
  True,
  False),
 ('WDC',
  'Western Digital Corporation',
  'Stock',
  'USD',
  'Technology',
  'Computer Hardware',
  'WDC',
  'WDC',
  'NASDAQ',
  'US9581021055',
  'Foreign Listed',
  True,
  False),
 ('WMS',
  'Advanced Drainage Systems, Inc.',
  'Stock',
  'USD',
  'Industrials',
  'Building Products & Equipment',
  'WMS',
  'WMS',
  'NYSE',
  'US00790R1041',
  'Foreign Listed',
  True,
  False),
 ('WMT',
  'Walmart Inc.',
  'Stock',
  'USD',
  'Consumer Defensive',
  'Discount Stores',
  'WMT',
  'WMT',
  'NASDAQ',
  'CA93267J1012',
  'Foreign Listed',
  True,
  False),
 ('WTRG',
  'Essential Utilities, Inc.',
  'Stock',
  'USD',
  'Utilities',
  'Utilities - Regulated Water',
  'WTRG',
  'WTRG',
  'NYSE',
  'US29670G1022',
  None,
  True,
  False),
 ('WTS',
  'Watts Water Technologies, Inc. (Class A)',
  'Stock',
  'USD',
  'Industrials',
  'Specialty Industrial Machinery',
  'WTS',
  'WTS',
  'NYSE',
  'US9427491025',
  'Foreign Listed',
  True,
  False),
 ('XOM',
  'Exxon Mobil Corporation',
  'Stock',
  'USD',
  'Energy',
  'Oil & Gas Integrated',
  'XOM',
  'XOM',
  'NYSE',
  'US30231G1022',
  'Foreign Listed',
  True,
  False),
 ('XPEV',
  'Xpeng Inc',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Auto Manufacturers',
  'XPEV',
  'XPEV',
  'NYSE',
  'US98422D1054',
  'Foreign Listed',
  True,
  False),
 ('XYL',
  'Xylem Inc.',
  'Stock',
  'USD',
  'Industrials',
  'Specialty Industrial Machinery',
  'XYL',
  'XYL',
  'NYSE',
  'US98419M1009',
  'Foreign Listed Shares (30% Dividend)',
  True,
  False),
 ('YUMC',
  'Yum China Holdings, Inc.',
  'Stock',
  'USD',
  'Consumer Cyclical',
  'Restaurants',
  'YUMC',
  'YUMC',
  'NYSE',
  'US98850P1093',
  'Foreign Listed',
  True,
  False)]

# (old_id, name, old_parent_id, type) -- old_id/old_parent_id are from the source install,
# used only to rebuild parent/child relationships on insert; not the ids in a fresh DB.
CATEGORIES = [(2, 'Consulting Income', None, 'Income'),
 (3, 'Employer Benefit', None, 'Income'),
 (4, 'Dental', 3, 'Income'),
 (5, 'Medical', 3, 'Income'),
 (6, 'Vision', 3, 'Income'),
 (7, 'Investment Income', None, 'Income'),
 (9, 'Other Business Income', None, 'Income'),
 (10, 'Other Income', None, 'Income'),
 (11, 'Child Support Received', 10, 'Income'),
 (12, 'Freelance', 10, 'Income'),
 (13, 'Gambling', 10, 'Income'),
 (14, 'Gifts Received', 10, 'Income'),
 (15, 'Government Support Received', 10, 'Income'),
 (16, 'Loan Principal Received', 10, 'Income'),
 (17, 'Lotteries', 10, 'Income'),
 (18, 'Sell Used Items', 10, 'Income'),
 (19, 'State & Local Tax Refund', 10, 'Income'),
 (20, 'Unemployment Compensation', 10, 'Income'),
 (21, 'Profit Sharing', None, 'Income'),
 (22, 'Reimbursed Business Expenses', None, 'Income'),
 (23, 'Business Car Expenses', 22, 'Income'),
 (24, 'Business Lunch', 22, 'Income'),
 (25, 'Business Travel', 22, 'Income'),
 (26, 'Reimbursed Expenses', None, 'Income'),
 (27, 'Bank Charges', 26, 'Income'),
 (28, 'Credit Card Return', 26, 'Income'),
 (29, 'Gifts', 26, 'Income'),
 (30, 'Insurance', 26, 'Income'),
 (31, 'Mobiles', 26, 'Income'),
 (32, 'Other', 26, 'Income'),
 (33, 'Petrol', 26, 'Income'),
 (34, 'Tips', 26, 'Income'),
 (35, 'Vacation', 26, 'Income'),
 (36, 'Value Added Tax', 26, 'Income'),
 (37, 'Wrong Charge', 26, 'Income'),
 (38, 'Retirement Income', None, 'Income'),
 (39, 'IRA Distributions', 38, 'Income'),
 (40, 'Pensions & Annuities', 38, 'Income'),
 (41, 'Social Security Benefits', 38, 'Income'),
 (46, 'Sales Income', None, 'Income'),
 (47, 'Cosmetics', 46, 'Income'),
 (48, 'Hardware', 46, 'Income'),
 (49, 'Tax Return', None, 'Income'),
 (50, 'Wages & Salary', None, 'Income'),
 (51, 'Benefit In Kind', 50, 'Income'),
 (52, 'Bonus', 50, 'Income'),
 (53, 'Car Allowance', 50, 'Income'),
 (54, 'Christmas Bonus', 50, 'Income'),
 (55, 'Commission', 50, 'Income'),
 (56, 'Easter Bonus', 50, 'Income'),
 (57, 'Pension Allowance', 50, 'Income'),
 (58, 'Gross Pay', 50, 'Income'),
 (59, 'Lumpsum', 50, 'Income'),
 (60, 'Net Pay', 50, 'Income'),
 (61, 'Not Taken Holidays', 50, 'Income'),
 (62, 'Overtime', 50, 'Income'),
 (63, 'Summer Vacation Bonus', 50, 'Income'),
 (64, 'Teleworking Allowance', 50, 'Income'),
 (65, '_401Contrib', None, 'Income'),
 (66, '_401ContribSpouse', None, 'Income'),
 (67, '_401EmployerContrib', None, 'Income'),
 (68, '_401EmployerContribSpouse', None, 'Income'),
 (69, '_401Withdrawal', None, 'Income'),
 (70, '_401WithdrawalSpouse', None, 'Income'),
 (71, '_DepCareContrib', None, 'Income'),
 (72, '_DivInc', None, 'Dividend'),
 (73, '_DivIncTaxFree', None, 'Dividend'),
 (74, '_EmpStkOptInc', None, 'Income'),
 (75, '_EmpStkOptIncSpouse', None, 'Income'),
 (76, '_ESPP Self Income', None, 'Income'),
 (77, '_ESPP Spouse Income', None, 'Income'),
 (78, '_FlexContrib', None, 'Income'),
 (79, '_IntInc', None, 'Interest'),
 (80, '_IntIncTaxFree', None, 'Interest'),
 (81, '_LT CapGnDst', None, 'Income'),
 (82, '_MT CapGnDst', None, 'Income'),
 (83, '_QualDivInc', None, 'Income'),
 (85, '_ST CapGnDst', None, 'Income'),
 (86, '_UnrlzdGain', None, 'Trading'),
 (87, 'Accessories', 306, 'Expense'),
 (88, 'Automobile', None, 'Expense'),
 (89, 'Accessories', 88, 'Expense'),
 (90, 'Car Payment', 88, 'Expense'),
 (91, 'Car Wash', 88, 'Expense'),
 (92, 'Depreciation', 88, 'Expense'),
 (93, 'Gasoline', 88, 'Expense'),
 (94, 'Insurance', 88, 'Expense'),
 (95, 'Maintenance', 88, 'Expense'),
 (96, 'Automobile (Business)', None, 'Expense'),
 (97, 'Insurance', 96, 'Expense'),
 (98, 'Bank Charges', None, 'Expense'),
 (99, 'Commission', 98, 'Expense'),
 (100, 'Credit Card Subscription', 98, 'Expense'),
 (101, 'Debit Card Renewal', 98, 'Expense'),
 (102, 'Debit Card Subscription', 98, 'Expense'),
 (103, 'Foreign Check Charge', 98, 'Expense'),
 (104, 'Foreign Credit Card Payment Charge', 98, 'Expense'),
 (105, 'Instant Money Transfer Charge', 98, 'Expense'),
 (106, 'Instant Payment Charge', 98, 'Expense'),
 (107, 'Interest Paid', 98, 'Expense'),
 (108, 'Money Transfer', 98, 'Expense'),
 (109, 'Payment Fees', 98, 'Expense'),
 (110, 'Prepaid Card Charge Fees', 98, 'Expense'),
 (111, 'Service Charge', 98, 'Expense'),
 (112, 'Bills', None, 'Expense'),
 (113, 'ADSL Service', 112, 'Expense'),
 (114, 'Cable TV', 112, 'Expense'),
 (115, 'Cellular', 112, 'Expense'),
 (118, 'Eleni', 115, 'Expense'),
 (122, 'Electricity', 112, 'Expense'),
 (123, 'Elevator', 112, 'Expense'),
 (124, "Homeowner's Dues", 112, 'Expense'),
 (125, 'Membership Fees', 112, 'Expense'),
 (126, 'Municipal Fees', 112, 'Expense'),
 (127, 'National Radio Television', 112, 'Expense'),
 (128, 'Natural Gas-Oil', 112, 'Expense'),
 (129, 'Newspaper', 112, 'Expense'),
 (130, 'Online-Internet Service', 112, 'Expense'),
 (131, 'Refreshed Energy Sources', 112, 'Expense'),
 (132, 'Telephone & Internet', 112, 'Expense'),
 (133, 'Water & Sewer', 112, 'Expense'),
 (134, 'Business Expenses (Not Reimbursed)', None, 'Expense'),
 (135, 'Accounting Fees', 134, 'Expense'),
 (136, 'Airfare', 134, 'Expense'),
 (137, 'Bank Charges', 134, 'Expense'),
 (138, 'Bills', 134, 'Expense'),
 (139, 'Electricity', 138, 'Expense'),
 (140, 'Telephone & Internet', 138, 'Expense'),
 (141, 'Water & Sewer', 138, 'Expense'),
 (142, 'Coffee', 134, 'Expense'),
 (143, 'Lodging', 134, 'Expense'),
 (144, 'Meals', 134, 'Expense'),
 (145, 'Other', 134, 'Expense'),
 (146, 'Parking', 134, 'Expense'),
 (147, 'Public Transport', 134, 'Expense'),
 (148, 'Taxi', 134, 'Expense'),
 (149, 'Tips', 134, 'Expense'),
 (150, 'Business Expenses (Reimbursed)', None, 'Expense'),
 (151, 'Bank Charges', 150, 'Expense'),
 (152, 'Car Maintenance', 150, 'Expense'),
 (153, 'Car Rental', 150, 'Expense'),
 (154, 'Car Wash', 150, 'Expense'),
 (155, 'Entertainment', 150, 'Expense'),
 (156, 'Flight Tickets', 150, 'Expense'),
 (157, 'Lodging', 150, 'Expense'),
 (158, 'Meals', 150, 'Expense'),
 (159, 'Medical Care', 150, 'Expense'),
 (160, 'Mobiles (Phone & Internet)', 150, 'Expense'),
 (161, 'Other', 150, 'Expense'),
 (162, 'Parking', 150, 'Expense'),
 (163, 'Petrol', 150, 'Expense'),
 (164, 'Public Transport', 150, 'Expense'),
 (165, 'Taxi', 150, 'Expense'),
 (166, 'Tips', 150, 'Expense'),
 (167, 'Tolls', 150, 'Expense'),
 (168, 'VISA', 150, 'Expense'),
 (170, 'Cell Phone', None, 'Expense'),
 (171, 'Charitable Donations', None, 'Expense'),
 (172, 'Childcare', None, 'Expense'),
 (173, 'Nursary', 172, 'Expense'),
 (174, 'Clothing', None, 'Expense'),
 (180, 'Commissions', None, 'Expense'),
 (181, 'Computers', None, 'Expense'),
 (182, 'Accessories', 181, 'Expense'),
 (183, 'Cloud Storage', 181, 'Expense'),
 (184, 'Computer Parts - Upgrade', 181, 'Expense'),
 (185, 'Computer Repair - Maintenance', 181, 'Expense'),
 (186, 'Computer Software', 181, 'Expense'),
 (187, 'Laptop', 181, 'Expense'),
 (188, 'Dues', None, 'Expense'),
 (189, 'Education', None, 'Expense'),
 (190, 'BasketBall Training', 189, 'Expense'),
 (192, 'Books', 189, 'Expense'),
 (193, 'Certificates', 189, 'Expense'),
 (194, 'Dancing Lessons', 189, 'Expense'),
 (195, 'Drama Courses', 189, 'Expense'),
 (196, 'Driving Lessons', 189, 'Expense'),
 (197, 'Excursions', 189, 'Expense'),
 (198, 'Language Books', 189, 'Expense'),
 (202, 'Language Courses', 189, 'Expense'),
 (206, 'Muay Thai Training', 189, 'Expense'),
 (209, 'Music Lessons', 189, 'Expense'),
 (210, 'Musical Instruments', 189, 'Expense'),
 (211, 'Ping-Pong Training', 189, 'Expense'),
 (212, 'Profile Analysis', 189, 'Expense'),
 (213, 'School Books', 189, 'Expense'),
 (214, 'School Courses', 189, 'Expense'),
 (218, 'School Material', 189, 'Expense'),
 (219, 'School Photos', 189, 'Expense'),
 (220, 'Seminars', 189, 'Expense'),
 (221, 'Soccer Training', 189, 'Expense'),
 (222, 'Souvenirs', 189, 'Expense'),
 (223, 'Subscriptions', 189, 'Expense'),
 (224, 'Swimming Lessons', 189, 'Expense'),
 (225, 'Table Tennis Training', 189, 'Expense'),
 (227, 'Water Polo Training', 189, 'Expense'),
 (228, 'Electronics', None, 'Expense'),
 (229, 'Adapters', 228, 'Expense'),
 (230, 'AV Equipment', 228, 'Expense'),
 (231, 'Batteries', 228, 'Expense'),
 (232, 'Cables', 228, 'Expense'),
 (233, 'CD-R', 228, 'Expense'),
 (234, 'Chargers', 228, 'Expense'),
 (235, 'DECT Phones', 228, 'Expense'),
 (236, 'DVD Recordable', 228, 'Expense'),
 (237, 'Gadgets', 228, 'Expense'),
 (238, 'Game Accessories', 228, 'Expense'),
 (239, 'Game Consoles', 228, 'Expense'),
 (240, 'Instruments', 228, 'Expense'),
 (241, 'Mobile Accessories', 228, 'Expense'),
 (242, 'Mobile Phones', 228, 'Expense'),
 (243, 'Network Equipment', 228, 'Expense'),
 (244, 'Video Tapes & Films', 228, 'Expense'),
 (245, 'Equipment Rental', None, 'Expense'),
 (246, 'Equipment Repair', None, 'Expense'),
 (247, 'Family Expenses', None, 'Expense'),
 (248, 'Pocket Money', 247, 'Expense'),
 (249, 'Public Transport', 247, 'Expense'),
 (250, 'Food', None, 'Expense'),
 (251, 'Alcohol Drinks', 250, 'Expense'),
 (252, 'Bread', 250, 'Expense'),
 (253, 'Cheese', 250, 'Expense'),
 (254, 'Chips', 250, 'Expense'),
 (255, 'Chocolates', 250, 'Expense'),
 (256, 'Coffee', 250, 'Expense'),
 (257, 'Delivery', 250, 'Expense'),
 (258, 'Diet Food', 250, 'Expense'),
 (259, 'Dining Out', 250, 'Expense'),
 (260, 'Fast Food', 250, 'Expense'),
 (261, 'Gums', 250, 'Expense'),
 (262, 'Ice Cream', 250, 'Expense'),
 (263, 'Milk', 250, 'Expense'),
 (264, 'Nuts', 250, 'Expense'),
 (265, 'Soft Drinks', 250, 'Expense'),
 (266, 'Sweet', 250, 'Expense'),
 (267, 'Friends Support', None, 'Expense'),
 (268, 'Gifts', None, 'Expense'),
 (269, 'Anniversaries', 268, 'Expense'),
 (270, 'Birthdays', 268, 'Expense'),
 (276, 'Christmas Carols', 268, 'Expense'),
 (277, 'Holidays', 268, 'Expense'),
 (282, 'Namedays', 268, 'Expense'),
 (283, 'Public Relations', 268, 'Expense'),
 (284, 'Souvenirs', 268, 'Expense'),
 (285, 'Special Events', 268, 'Expense'),
 (286, 'Wedding & Baptism', 268, 'Expense'),
 (287, 'Groceries', None, 'Expense'),
 (288, 'Healthcare', None, 'Expense'),
 (289, 'Accessories', 288, 'Expense'),
 (290, 'Anesthesiologist', 288, 'Expense'),
 (291, 'Check-up', 288, 'Expense'),
 (292, 'Dental', 288, 'Expense'),
 (293, 'Diet Doctor', 288, 'Expense'),
 (294, 'Energy Therapy', 288, 'Expense'),
 (295, 'ENT', 288, 'Expense'),
 (296, 'Eyecare', 288, 'Expense'),
 (297, 'Hospital', 288, 'Expense'),
 (298, 'Orthopedic', 288, 'Expense'),
 (299, 'Pathologist', 288, 'Expense'),
 (300, 'Physician', 288, 'Expense'),
 (301, 'Pregnancy', 288, 'Expense'),
 (302, 'Prescriptions', 288, 'Expense'),
 (303, 'Psychiatrist', 288, 'Expense'),
 (304, 'Psychologist', 288, 'Expense'),
 (305, 'Surgeror', 288, 'Expense'),
 (306, 'Household', None, 'Expense'),
 (307, 'Furnishings', 306, 'Expense'),
 (308, 'Gadgets', 306, 'Expense'),
 (309, 'House Cleaning', 306, 'Expense'),
 (310, 'Laundry', 306, 'Expense'),
 (311, 'Maintenance', 306, 'Expense'),
 (312, 'Super Market', 306, 'Expense'),
 (313, 'Yard Service', 306, 'Expense'),
 (314, 'Insurance', None, 'Expense'),
 (315, 'Health', 314, 'Expense'),
 (316, "Homeowner's-Renter's", 314, 'Expense'),
 (317, 'Life', 314, 'Expense'),
 (318, 'Pension', 314, 'Expense'),
 (319, 'Interest Expense', None, 'Interest'),
 (320, 'Inventory Purchases', None, 'Expense'),
 (321, 'Investment Expenses', None, 'Expense'),
 (322, 'Accounting Fees', 321, 'Expense'),
 (323, 'Default', 321, 'Expense'),
 (324, 'Lawyer Fees', 321, 'Expense'),
 (325, 'Position Fees', 321, 'Expense'),
 (326, 'Transfer Fees', 321, 'Expense'),
 (327, 'Job Expense', None, 'Expense'),
 (328, 'Non-Reimbursed', 327, 'Expense'),
 (329, 'Reimbursed', 327, 'Expense'),
 (330, 'Legal Fees', None, 'Expense'),
 (331, 'Leisure', None, 'Expense'),
 (332, 'Books & Magazines', 331, 'Expense'),
 (333, 'Cafe', 331, 'Expense'),
 (334, 'Cinema', 331, 'Expense'),
 (335, 'Cloud Services Subscriptions', 331, 'Expense'),
 (336, 'Cultural Events', 331, 'Expense'),
 (337, 'Entertaining', 331, 'Expense'),
 (338, 'Gambling', 331, 'Expense'),
 (339, 'Gym', 331, 'Expense'),
 (340, 'Hobby', 331, 'Expense'),
 (341, 'Movies & Video Rentals', 331, 'Expense'),
 (342, 'Music Rentals', 331, 'Expense'),
 (343, 'Parking', 331, 'Expense'),
 (344, 'Parties', 331, 'Expense'),
 (346, 'Photos', 331, 'Expense'),
 (347, 'SPA & Massage', 331, 'Expense'),
 (348, 'Sporting Accessories', 331, 'Expense'),
 (349, 'Sporting Events', 331, 'Expense'),
 (350, 'Sporting Goods', 331, 'Expense'),
 (351, 'Sporting Materials Maintenance', 331, 'Expense'),
 (352, 'Sporting Subscriptions', 331, 'Expense'),
 (353, 'Summer Camp', 331, 'Expense'),
 (354, 'Tapes & CDs', 331, 'Expense'),
 (355, 'Theater', 331, 'Expense'),
 (356, 'Tips', 331, 'Expense'),
 (357, 'Toys & Games', 331, 'Expense'),
 (358, 'Vinyl', 331, 'Expense'),
 (359, 'Licenses and Permits', None, 'Expense'),
 (360, 'Loan', None, 'Expense'),
 (361, 'Administration Fees', 360, 'Expense'),
 (362, 'Car Interest', 360, 'Interest'),
 (363, 'Loan Interest', 360, 'Interest'),
 (364, 'Mortgage Interest', 360, 'Interest'),
 (365, 'Student Loan Interest', 360, 'Interest'),
 (366, 'Mam Support', None, 'Expense'),
 (367, 'Bills', 366, 'Expense'),
 (368, 'ENFIA', 366, 'Expense'),
 (369, 'House Maintenance', 366, 'Expense'),
 (370, 'Tax', 366, 'Expense'),
 (371, 'Miscallaneous (Reimbursed)', None, 'Expense'),
 (372, 'Miscellaneous', None, 'Expense'),
 (373, 'Miscellaneous (Business)', None, 'Expense'),
 (374, 'About Aura', 373, 'Expense'),
 (375, 'Energy Healing', 373, 'Expense'),
 (376, 'Web Services', 375, 'Expense'),
 (377, 'Hardware', 373, 'Expense'),
 (378, 'Nutrimetics', 373, 'Expense'),
 (379, 'Yves Rocher', 373, 'Expense'),
 (380, 'Events', 379, 'Expense'),
 (381, 'Products', 379, 'Expense'),
 (382, 'Tools', 379, 'Expense'),
 (383, 'Trips', 379, 'Expense'),
 (384, 'Not Sure, Biz', None, 'Expense'),
 (385, 'Not Sure, Rental', None, 'Expense'),
 (386, 'Office Maintenance', None, 'Expense'),
 (387, 'Office Phone', None, 'Expense'),
 (388, 'Office Rent', None, 'Expense'),
 (389, 'Office Supplies', None, 'Expense'),
 (390, 'Expendable', 389, 'Expense'),
 (391, 'Office Utilities', None, 'Expense'),
 (392, 'Other Business Expense', None, 'Expense'),
 (393, 'Outside Services', None, 'Expense'),
 (394, 'Personal Care', None, 'Expense'),
 (395, 'Body Care', 394, 'Expense'),
 (396, 'Cosmetics', 394, 'Expense'),
 (397, 'Hair Styling', 394, 'Expense'),
 (403, 'Shiatsou', 394, 'Expense'),
 (404, 'Pet Care', None, 'Expense'),
 (405, 'Accessories', 404, 'Expense'),
 (406, 'Bathing', 404, 'Expense'),
 (407, 'Check up', 404, 'Expense'),
 (408, 'Drugs', 404, 'Expense'),
 (409, 'Food', 404, 'Expense'),
 (410, 'Hair Cut', 404, 'Expense'),
 (411, 'Hotel', 404, 'Expense'),
 (412, 'Pet', 404, 'Expense'),
 (413, 'Supplies', 404, 'Expense'),
 (414, 'Surgery', 404, 'Expense'),
 (415, 'Veterinarian', 404, 'Expense'),
 (416, 'Postage-Delivery', None, 'Expense'),
 (417, 'Printing-Copying', None, 'Expense'),
 (418, 'Professional Development', None, 'Expense'),
 (419, 'Rounding', None, 'Expense'),
 (420, 'Smoking', None, 'Expense'),
 (421, 'Accessories', 420, 'Expense'),
 (422, 'Cigarettes', 420, 'Expense'),
 (423, 'Cigars', 420, 'Expense'),
 (424, 'Steaming', 420, 'Expense'),
 (425, 'Special Events', None, 'Expense'),
 (426, 'Subscriptions', 134, 'Expense'),
 (427, 'Tax', None, 'Tax'),
 (428, 'Fed', 427, 'Tax'),
 (429, 'Medicare', 427, 'Tax'),
 (430, 'Other', 427, 'Tax'),
 (431, 'SDI', 427, 'Tax'),
 (432, 'Soc Sec', 427, 'Tax'),
 (433, 'State', 427, 'Tax'),
 (434, 'Tax Preparation-Advice', None, 'Expense'),
 (435, 'Taxes', None, 'Tax'),
 (436, 'Business VAT', 435, 'Tax'),
 (437, 'Federal Income Tax', 435, 'Tax'),
 (438, 'Federal Income Tax-Previous Year', 435, 'Tax'),
 (439, 'Interest Taxes', 435, 'Tax'),
 (440, 'Investment Income Taxes', 435, 'Tax'),
 (441, 'Local Income Tax', 435, 'Tax'),
 (442, 'Medicare Tax', 435, 'Tax'),
 (443, 'Other Taxes', 435, 'Tax'),
 (444, 'Penalty', 435, 'Tax'),
 (445, 'Real Estate Taxes', 435, 'Tax'),
 (446, 'Sales Tax', 435, 'Tax'),
 (447, 'Social Security Tax', 435, 'Tax'),
 (448, 'State Income Tax', 435, 'Tax'),
 (449, 'State-Provincial', 435, 'Tax'),
 (450, 'Tolls', 435, 'Tax'),
 (451, 'Vehicle Tax', 435, 'Tax'),
 (452, 'Vacation', None, 'Expense'),
 (453, 'Cafe', 452, 'Expense'),
 (454, 'Chips', 452, 'Expense'),
 (455, 'Dining Out', 452, 'Expense'),
 (456, 'Drinks', 452, 'Expense'),
 (457, 'Fast Food', 452, 'Expense'),
 (458, 'Fruit', 452, 'Expense'),
 (459, 'Ice Cream', 452, 'Expense'),
 (462, 'Lodging', 452, 'Expense'),
 (463, 'Electricity', 462, 'Expense'),
 (464, 'Internet', 462, 'Expense'),
 (465, 'Maintenance', 462, 'Expense'),
 (466, 'Municipal Fees', 462, 'Expense'),
 (467, 'National Radio Television', 462, 'Expense'),
 (468, 'Taxes', 462, 'Expense'),
 (470, 'Telephone & Internet', 462, 'Expense'),
 (471, 'Water', 462, 'Expense'),
 (473, 'Mini Bar', 452, 'Expense'),
 (474, 'Mini Market', 452, 'Expense'),
 (475, 'Night Life', 452, 'Expense'),
 (478, 'Other', 452, 'Expense'),
 (479, 'Shopping', 452, 'Expense'),
 (480, 'Soft Drinks', 452, 'Expense'),
 (481, 'Tips', 452, 'Expense'),
 (482, 'Travel', 452, 'Expense'),
 (483, 'Wages Paid', None, 'Expense'),
 (484, '_401FedWithheld', None, 'Expense'),
 (485, '_401FedWithheldSpouse', None, 'Expense'),
 (486, '_401StateWithheld', None, 'Expense'),
 (487, '_401StateWithheldSpouse', None, 'Expense'),
 (488, '_401WithdrawalPenalty', None, 'Expense'),
 (489, '_401WithdrawalPenaltySpouse', None, 'Expense'),
 (490, '_Accrued Int', None, 'Interest'),
 (491, '_Accrued Int TaxFree', None, 'Interest'),
 (492, '_IntExp', None, 'Interest'),
 (493, '_MileageBus', None, 'Expense'),
 (494, '_MileageChrity', None, 'Expense'),
 (495, '_MileageMedl', None, 'Expense'),
 (496, '_MileageOthr', None, 'Expense'),
 (497, '_MileageRentl', None, 'Expense'),
 (498, '_MileageUnreimBus', None, 'Expense'),
 (617, '_MiscExp', None, 'Expense'),
 (714, 'Bonus', None, 'Income'),
 (715, 'Dermatologist', 288, 'Expense'),
 (720, 'Business Gifts', 134, 'Expense'),
 (721, 'Business Gifts', 150, 'Expense'),
 (724, '_RlzdPnL', None, 'Trading'),
 (725, 'Subscriptions', 150, 'Expense'),
 (726, 'Subscriptions', 372, 'Expense'),
 (728, 'Web Services', 373, 'Expense'),
 (732, 'Sweet', 452, 'Expense')]

PAYEES = ['Opening Balance',
 'Opening Cash Balance',
 'Balance Adjustment',
 'Transfer Money',
 'Miscellaneous',
 'Other',
 'Airport',
 'Airport Lounge',
 'Airport Parking',
 'Bakery',
 'Bar',
 'Beach Bar',
 'Bicycles Store',
 'Book Store',
 "Butcher's Shop",
 'Cafe',
 'Car Service',
 'Car Wash',
 'Carpets Cleaning',
 'Catering',
 'Church',
 'Cinema',
 'Clothes Store',
 'Console Club',
 'Cook Shop',
 'Dental Services',
 'Doctor',
 'Duty Free Shops',
 'Exhibition',
 'Fast Food',
 'Ferries',
 'Fishing Store',
 'Fishmonger',
 'Flower Shop',
 'Garden Store',
 'Gas Station',
 'Gift Shop',
 'Gift Store',
 'Grocery',
 'Hospital',
 'Hotel',
 'House Cleaning',
 'Kiosk',
 'Laundry',
 'Mini Market',
 'Museum',
 'Music Store',
 'Night Club',
 'Nursery',
 'Parking',
 'Patisserie',
 'Pet Shop',
 'Pharmacy',
 'Physicotherapist',
 'Plumber',
 'Post Office',
 'Psychiatrist',
 'Restaurant',
 'School',
 'Sports Store',
 'Super Market',
 'Taxi',
 'Theater',
 'Tobacco Store',
 'Toy Store',
 'Train',
 'Tram',
 'Travel Agency',
 'Mutual Funds',
 'Robo-Advisor',
 'Amazon.com',
 'Netflix',
 'Spotify',
 'Google',
 'Microsoft',
 'Microsoft Store',
 'Uber',
 'Bolt',
 'Booking.Com',
 'IKEA',
 'H&M',
 'Zara',
 'Zara Home',
 'Decathlon',
 'Nike',
 'Adidas',
 'Puma',
 "Levi's",
 'Foot Locker',
 'Marks & Spencer',
 'GAP',
 'Sephora',
 'PayPal',
 'DHL',
 'EasyJet',
 'RyanAir',
 'KLM',
 'Emirates',
 'AVIS',
 'Ebay',
 'Wish.com',
 'Shein',
 'Temu',
 'Steam Games',
 'PlayStation Network',
 'Epic Games International',
 'Ubisoft',
 'EA Sports',
 'Facebook',
 'iTunes',
 'Five Guys',
 'Hard Rock Cafe',
 'Victoria Secret',
 'Swarovski',
 'Timberland Store',
 'Skechers',
 'Louis Vuitton',
 'Versace',
 'Valentino',
 'Klarna',
 'Groupon',
 'Lenovo',
 'Media Markt',
 'FNAC',
 'Vodafone',
 'Wolt',
 'Hermes']
