-- Installment series v2: decouples installment generation from template recurrence.
-- Total_Occurrences no longer deactivates the template after one series. Instead, each
-- cycle's draft (generated by the template's own unchanged Periodicity/Next_Due_Date/
-- End_Date-driven cycle), once confirmed, expands into a fresh N-installment series spaced
-- by the new Installment_Frequency field -- while the template itself keeps recurring
-- indefinitely, spawning a brand-new series every time it comes due again. See
-- database/queries.py::_maybe_expand_installment_series and
-- database/migrations/015_installment_templates.sql (the original Total_Occurrences addition,
-- unchanged by this migration).

ALTER TABLE Recurring_Templates ADD COLUMN IF NOT EXISTS Installment_Frequency VARCHAR(20);

ALTER TABLE Transactions ADD COLUMN IF NOT EXISTS Installment_Group_Id INTEGER;
ALTER TABLE Transactions ADD COLUMN IF NOT EXISTS Installment_Seq INTEGER;

CREATE INDEX IF NOT EXISTS idx_transactions_installment_group
    ON Transactions(Installment_Group_Id) WHERE Installment_Group_Id IS NOT NULL;
